name: 'Docker'
description: 'Build, push and deploy to container registry'
inputs:
  directory:
    description: 'The Terraform directory'
    required: false
    default: ./.terraform
  values:
    description: 'The Terraform values in JSON'
    required: false
outputs:
  image:
    description: 'The image'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.values }}