name: 'Docker'
description: 'Build, push and deploy to container registry'
inputs:
  username:
    description: 'Username to authenticate to the registry'
    required: true
  password:
    description: 'Password to authenticate to the registry'
    required: true
  registry:
    description: 'Registry URL'
    required: true
    default: ghcr.io
  image-name:
    description: 'The image name'
    required: true
  version:
    description: 'Image version'
    required: true
    default: latest
  dockerfile:
    description: 'Path of the Dockerfile'
    required: true
    default: Dockerfile
  context:
    description: 'Path of the context'
    required: true
    default: .
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.registry }}
    - ${{ inputs.image-name }}
    - ${{ inputs.version }}
    - ${{ inputs.dockerfile }}
    - ${{ inputs.context }}